apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-licr
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-licr
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-licr
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-licr
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-licr
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-arox-tenant/rhtap-demo-app/hacbs-test-project-licr@sha256:b2b3335802070a84ca0b260b54e4ceed1bc97288bdceddb9d8144d0b0a8a6835
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
