apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-licr
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-arox-tenant/rhtap-demo-app/hacbs-test-project-licr@sha256:acfe9dbabe8bc12afeea0435673fd50325defe7d7caf6b497ebcd9b4f9143053
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
