apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-licr
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-arox-tenant/rhtap-demo-app/hacbs-test-project-licr@sha256:b2b3335802070a84ca0b260b54e4ceed1bc97288bdceddb9d8144d0b0a8a6835
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
